# Generated by Django 4.2.23 on 2025-07-09 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Full company/organization name", max_length=255
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("US/Eastern", "US/Eastern"),
                            ("US/Central", "US/Central"),
                            ("US/Mountain", "US/Mountain"),
                            ("US/Pacific", "US/Pacific"),
                            ("Europe/London", "Europe/London"),
                            ("Europe/Paris", "Europe/Paris"),
                            ("Asia/Tokyo", "Asia/Tokyo"),
                            ("Asia/Shanghai", "Asia/Shanghai"),
                            ("Asia/Kolkata", "Asia/Kolkata"),
                            ("Australia/Sydney", "Australia/Sydney"),
                        ],
                        default="UTC",
                        help_text="Primary timezone for this account",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this account is currently active",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email for this account",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="United States", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of users allowed for this account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "ordering": ["account_name"],
            },
        ),
    ]
