# Generated by Django 4.2.23 on 2025-07-09 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="not_started",
                        help_text="Current status of this journey",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Date when the journey started", null=True
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected completion date based on template duration",
                        null=True,
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, help_text="Actual completion date", null=True
                    ),
                ),
                (
                    "total_steps",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of steps in this journey"
                    ),
                ),
                (
                    "completed_steps",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed steps"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this journey instance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journey Instance",
                "verbose_name_plural": "Journey Instances",
                "db_table": "journey_instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the step (e.g., Complete HR Orientation)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed instructions for this step"
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("orientation", "Orientation"),
                            ("documentation", "Documentation"),
                            ("training", "Training"),
                            ("system_access", "System Access"),
                            ("equipment", "Equipment Setup"),
                            ("meeting", "Meeting/Interview"),
                            ("review", "Review/Approval"),
                            ("handover", "Handover"),
                            ("exit_interview", "Exit Interview"),
                            ("asset_return", "Asset Return"),
                            ("access_revocation", "Access Revocation"),
                            ("final_settlement", "Final Settlement"),
                            ("other", "Other"),
                        ],
                        help_text="Category/type of this step",
                        max_length=50,
                    ),
                ),
                (
                    "responsible_role",
                    models.CharField(
                        blank=True,
                        help_text="Role responsible for this step (e.g., HR, IT Admin, Manager)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "due_days_from_start",
                    models.PositiveIntegerField(
                        help_text="Number of days from journey start when this step is due"
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated time to complete this step (in hours)",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of this step in the journey"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this step is mandatory for journey completion",
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Whether subsequent steps cannot start until this is completed",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this step requires approval to mark as complete",
                    ),
                ),
                (
                    "auto_assign",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this step should be auto-assigned when journey starts",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or requirements for this step",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this step is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journey Step",
                "verbose_name_plural": "Journey Steps",
                "db_table": "journey_steps",
                "ordering": ["template", "order", "due_days_from_start"],
            },
        ),
        migrations.CreateModel(
            name="JourneyStepInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        help_text="Current status of this step",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(help_text="Date when this step is due")),
                (
                    "started_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When work on this step was started",
                        null=True,
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, help_text="When this step was completed", null=True
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(
                        blank=True, help_text="Notes about step completion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journey Step Instance",
                "verbose_name_plural": "Journey Step Instances",
                "db_table": "journey_step_instances",
                "ordering": ["journey", "step_template__order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "journey_type",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("offboarding", "Offboarding"),
                        ],
                        default="onboarding",
                        help_text="Type of journey this template represents",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for this journey template",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the boarding process",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department this template applies to (auto-filled from job title)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        blank=True,
                        help_text="Business unit this template applies to",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(
                        help_text="Estimated duration in days for completing this journey"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for the department/type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_templates",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Template",
                "verbose_name_plural": "Journey Templates",
                "db_table": "journey_templates",
                "ordering": ["journey_type", "department", "title"],
            },
        ),
    ]
