# Generated by Django 4.2.23 on 2025-07-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boarding", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journeytemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_journey_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeytemplate",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                help_text="Job title this template applies to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journey_templates",
                to="users.jobtitle",
            ),
        ),
        migrations.AddField(
            model_name="journeystepinstance",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to complete this step",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_step_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeystepinstance",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked this step as completed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_step_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeystepinstance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this step instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_step_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeystepinstance",
            name="journey",
            field=models.ForeignKey(
                help_text="Journey this step belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_instances",
                to="boarding.journeyinstance",
            ),
        ),
        migrations.AddField(
            model_name="journeystepinstance",
            name="step_template",
            field=models.ForeignKey(
                help_text="Template step this instance is based on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="boarding.journeystep",
            ),
        ),
        migrations.AddField(
            model_name="journeystep",
            name="responsible_party",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for completing this step",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_journey_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeystep",
            name="template",
            field=models.ForeignKey(
                help_text="Journey template this step belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="boarding.journeytemplate",
            ),
        ),
        migrations.AddField(
            model_name="journeyinstance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this journey instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_journey_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeyinstance",
            name="template",
            field=models.ForeignKey(
                help_text="Template this journey is based on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="boarding.journeytemplate",
            ),
        ),
        migrations.AddField(
            model_name="journeyinstance",
            name="user",
            field=models.ForeignKey(
                help_text="User undergoing this journey",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeytemplate",
            unique_together={("account", "journey_type", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="journeystep",
            unique_together={("template", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="journeyinstance",
            unique_together={("template", "user")},
        ),
    ]
