# Generated by Django 4.2.23 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0002_add_job_title_to_journey_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeytemplate",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department this template applies to (auto-filled from job title)",
                max_length=100,
                null=True,
            ),
        ),
    ]
