# Generated by Django 4.2.23 on 2025-07-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_account_id_and_more'),
        ('boarding', '0003_alter_journeytemplate_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journeytemplate',
            unique_together={('account', 'journey_type', 'title')},
        ),
        migrations.RemoveField(
            model_name='journeytemplate',
            name='job_title',
        ),
    ]
