# Generated by Django 4.2.23 on 2025-07-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_job_titles"),
        ("users", "0003_remove_unused_fields"),
    ]

    operations = []
