# Generated by Django 4.2.23 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_0002_add_job_titles_0003_remove_unused_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
            ),
        ),
    ]
