# Generated by Django 4.2.23 on 2025-07-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hire_date',
        ),
    ]
