# Generated by Django 4.2.23 on 2025-07-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_employee_id_remove_user_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='boarding_template_title',
        ),
    ]
