# Generated by Django 4.2.23 on 2025-07-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0004_alter_journeytemplate_unique_together_and_more'),
        ('users', '0008_remove_jobtitle_boarding_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Journey template assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='boarding.journeytemplate'),
        ),
    ]
